requires 'Amazon::Sites';
requires 'DBD::SQLite';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::ResultSetNames';
requires 'DateTime::Format::SQLite';
requires 'ENV::Util';
requires 'Moose';
requires 'MooseX::NonMoose';
requires 'MooX::Role::JSON_LD';
requires 'Path::Tiny', '0.125';
requires 'Template';
