#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

use PerlSchool::Schema;

my $sch = PerlSchool::Schema->get_schema;
my $rs  = $sch->resultset('Author');

my @cols = qw[title author slug subtitle amazon_isin leanpub_slug
              blurb examples pubdate is_perlschool_book];

while (<>) {
  chomp;
  my %book;

  @book{@cols} = map { $_ // undef } split /\|/;
  $book{image} = "$book{slug}";

  my $author = $rs->find({ name => $book{author}});

  unless ($author) {
    say "Creating author $book{author}";
    $author = $rs->create({
      name => $book{author},
      bio => "$book{author} bio",
    });
  }

  delete $book{author};

  $author->add_to_books(\%book);
}
