name: Generate web page

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install cpanm
      run: |
          sudo apt-get update -y
          sudo apt-get install -y cpanminus

    - name: Install modules
      run: |
          sudo cpanm --installdeps --notest .

    - name: Create pages
      run: |
        mkdir -p docs
        PERL5LIB=lib bin/build

    - name: Commit new page
      if: github.repository == 'davorg/perlschool'
      run: |
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add docs/
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated Web page generation"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi

    - name: Update pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

