name: Generate web page

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PERLSCHOOL_DB: ${{ vars.PERLSCHOOL_DB }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install cpanm
      run: |
          sudo apt-get update -y
          sudo apt-get install -y cpanminus

    - name: Install modules
      run: |
          sudo cpanm --installdeps --notest .

    - name: Create pages
      run: |
        mkdir -p docs
        PERL5LIB=lib bin/build

    - name: Update pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

